### ISSUE TITLE
Не изменяется значение rshares после снятия лайка/дизлайка

### ISSUE THREAD

**Issue by beautyfree** [GolosChain/prism-service#108]
Поведение:
При нажатии лайк/дизлайк, после снятия голоса значение rshares не изменяется

Ожидание:
На нажатие лайк/дизлайк изменяется значение rshares в большую/меньшую сторону, а при снятии лайка/дизлайка возвращается к значению на которое было изменение.

**Comment by Format-X22** [comment]
Не воспроизводится, возможно потому что что-то изменилось в новой версии.
