### ISSUE TITLE
Добавить в выдачу content.getFeed и content.getPost данные о количестве просмотров

### ISSUE THREAD

**Issue by Bacher** [GolosChain/prism-service#113]
Добавить поле `viewCount` в выдачу к постам в выдачу к:
* content.getFeed
* content.getPost

**Comment by Format-X22** [comment]
Необходимо прийти к консенсусу по поводу принципа реализации.

**Comment by Format-X22** [comment]
Не будет содержаться в текущем запросе, должен делаться отдельный запрос.
