### ISSUE TITLE
Маркировать конец ленты

### ISSUE THREAD

**Issue by yurivlad** [GolosChain/prism-service#124]
При выдаче коментов, если достигнуть конец ленты надо отдавать маркер конца ленты.
Например
{"id":4,"jsonrpc":"2.0","method":"content.getComments","params":{"limit":2,"permlink":"artemisfightswithhectoragainsthelios","refBlockNum":320697,"sequenceKey":"5c8797c0da342ce406cabb69","sortBy":"time","type":"post","userId":"tst2lwbafozq"}}
в ответ 1 комент и "sequenceKey":"5c8797c3da342c4a0acabb77"}}
т.е как я понимаю, если sequenceKey!= null это не конец ленты.

но {"id":5,"jsonrpc":"2.0","method":"content.getComments","params":{"limit":2,"permlink":"artemisfightswithhectoragainsthelios","refBlockNum":320697,"sequenceKey":"5c8797c3da342c4a0acabb77","sortBy":"time","type":"post","userId":"tst2lwbafozq"}}
on message {"jsonrpc":"2.0","id":5,"result":{"items":[],"sequenceKey":null}}

т.е ненулевой sequenceKey говорит он том что лента не кончилась, хотя это так.

**Comment by Format-X22** [comment]
Останется кейс когда ровно запрошенное количество элементов получено, а следующий запрос вернет пустоту т.к. не эффективно смотреть вперед на каждый запрос. Но во всех других случаях, когда по результату видно что что данных дальше уже нет - будет возвращаться null.
