### ISSUE TITLE
Запрос на ленту пропускает комментарии

### ISSUE THREAD

**Issue by yurivlad** [GolosChain/prism-service#125]
{"id":1,"jsonrpc":"2.0","method":"content.getFeed","params":{"communityId":"gls","limit":1,"sortBy":"time","type":"community"}}
первый пост - ,"contentId":{"userId":"tst2lwbafozq","permlink":"artemisfightswithhectoragainsthelios","refBlockNum":320697}
и "commentsCount":8 - пост с 8 коментариями

потом я запращиваю 3 комента-
"id":2,"jsonrpc":"2.0","method":"content.getComments","params":{"limit":3,"permlink":"artemisfightswithhectoragainsthelios","refBlockNum":320697,"sortBy":"time","type":"post","userId":"tst2lwbafozq"}
ответ - 3 комента, верно,

потом еще 3 комента прошу
{"id":3,"jsonrpc":"2.0","method":"content.getComments","params":{"limit":3,"permlink":"artemisfightswithhectoragainsthelios","refBlockNum":320697,"sequenceKey":"5c8797bdda342cbd97cabb4a","sortBy":"time","type":"post","userId":"tst2lwbafozq"}}
и опять в ответ 3 комента
итого - 6

я ожидаю в итоге 8, поэтому запрашиваю  {"id":4,"jsonrpc":"2.0","method":"content.getComments","params":{"limit":2,"permlink":"artemisfightswithhectoragainsthelios","refBlockNum":320697,"sequenceKey":"5c8797c0da342ce406cabb69","sortBy":"time","type":"post","userId":"tst2lwbafozq"}}
но в ответ получаю 1 комент.

Итого 7 != 8, 1 комментарий пропущен

**Comment by Format-X22** [comment]
Нужно сменить секвенс с айдишников на даты т.к. коллизии, исправлю.
