### ISSUE TITLE
Реализовать обработку репостов

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/prism-service#127]
1. Реализовать счетчик репостов оригинальной записи
2. Реализовать отображение репостов в ленте пользователя
3. Реализовать отображение лайков/дизлайков оригинальной записи //TODO актуализировать данный пункт

**Comment by Format-X22** [comment]
Нужно уточнение ТЗ.

**Comment by Format-X22** [comment]
Не ясно будет ли это вообще.

**Comment by Format-X22** [comment]
Будет только для ленты подписок и в личной ленте пользователя.
