### ISSUE TITLE
Пропало поле tags в постах

### ISSUE THREAD

**Issue by Bacher** [GolosChain/prism-service#151]
Вот тут есть tags в metadata, но нет поля tags в моделе.

![image.png](https://images.zenhubusercontent.com/5b0ff4b64b5806bc2bd5811e/f8009928-bd81-4026-8f5e-d223091fd67f)

**Comment by Format-X22** [comment]
Не воспроизводится, вероятно уже пофикшено. Если нет - нужен кейс.
