### ISSUE TITLE
звпрос getPost возвращает пустое  body

### ISSUE THREAD

**Issue by yurivlad** [GolosChain/prism-service#159]
Запрос {"id":1,"jsonrpc":"2.0","method":"content.getPost","params":{"contentType":"mobile","permlink":"hephaestusfightswithismeneagainstmetis","refBlockNum":833,"userId":"tst2jlhkxobs"}}

возвращает "result":{"content":{"body":{},"tags":[]

**Comment by Format-X22** [comment]
Актуально только для старых постов, то есть в данном случае не баг.
