### ISSUE TITLE
запрос getComments не возвращает поле mobile

### ISSUE THREAD

**Issue by yurivlad** [GolosChain/prism-service#160]
{“id”:7,“jsonrpc”:“2.0",“method”:“content.getComments”,“params”:{“contentType”:“mobile”,“limit”:20,“permlink”:“dionysusfightswithbriseisagainstepimetheus”,“refBlockNum”:802,“sortBy”:“time”,“type”:“post”,“userId”:“d5gqchmbgrdj”}}

*ответ*
{
  "jsonrpc": "2.0",
  "id": 7,
  "result": {
    "items": [
      {
        "parent": {
          "post": {
            "contentId": {
              "userId": "d5gqchmbgrdj",
              "permlink": "dionysusfightswithbriseisagainstepimetheus",
              "refBlockNum": 802
            }
          }
        },
        "content": {
          "body": {
            "full": "Chuck Norris's beard can type 140 wpm.\n at the moment he lives at Suite 750 04103 Harber Row, Kertzmannberg, DE 53031-3382 #feliznatal  @tst4wgqnfhmf   \n\n and YODA said: Good relations with the Wookiees, I have. \n\n witcher quote: Finish all your business before you die. Bid loved ones farewell. Write your will. Apologize to those you’ve wronged. Otherwise, you’ll never truly leave this world. \n\n Rick and Morty quote: You're our boy dog, don't even trip. \n\n SuperHero The Arachne has power to Enhanced Smell and Cross-Dimensional Travel \n\n Harry Potter quote: I solemnly swear I am up to no good. \n\n and some Lorem to finish text: Id voluptatem pariatur placeat unde quod quam ut optio qui et aut sunt officiis exercitationem nulla eos temporibus omnis sit est quidem et sunt fugit tempore rerum velit unde non eligendi laboriosam nisi aut architecto iste sunt commodi nihil minima accusamus aut sint quo dolore quibusdam officiis asperiores excepturi illum fugit omnis magni vitae assumenda et ipsa hic numquam exercitationem corporis vitae magni ut vel quo autem et maiores ut dolores laborum totam soluta natus et nobis et ducimus voluptas reprehenderit aut nostrum ut voluptates voluptatem aliquam vero aut ipsam fugiat molestias nisi distinctio possimus voluptas ut dolor et quia consequuntur fugit explicabo iusto tempora adipisci inventore temporibus vero id ad numquam eius et ut asperiores quia aut pariatur corrupti libero tempora velit nesciunt qui officiis autem exercitationem aperiam quo placeat perferendis reprehenderit sunt et non placeat voluptates delectus sed at aut earum consequatur incidunt aliquid maxime a voluptatem voluptatibus qui rerum."
          },
          "embeds": [
            {
              "_id": "5caf60692616bf2a5baa7fc9",
              "id": "85ffa24b-f29b-4fee-a484-e602956cf38a",
              "type": "oembed",
              "result": {
                "type": "video",
                "version": "1.0",
                "title": "Mr. Trololo original upload",
                "url": "https://www.youtube.com/watch?v=oavMtUWDBTM",
                "author": "RealPapaPit",
                "author_url": "https://www.youtube.com/user/RealPapaPit",
                "provider_name": "YouTube",
                "description": "Я очень рад, ведь я, наконец, возвращаюсь домой. Оригинальный клип. Исполняет Эдуард Хиль.",
                "thumbnail_url": "https://i.ytimg.com/vi/oavMtUWDBTM/hqdefault.jpg",
                "thumbnail_width": 480,
                "thumbnail_height": 360,
                "html": "<div><div style=\"left: 0; width: 100%; height: 0; position: relative; padding-bottom: 74.9457%;\"><iframe src=\"https://www.youtube.com/embed/oavMtUWDBTM?feature=oembed\" style=\"border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute;\" allowfullscreen scrolling=\"no\"></iframe></div></div>"
              }
            }
          ]
        },
        "payout": {
          "rShares": 13347805654144
        },
        "votes": {
          "upCount": 1,
          "downCount": 0,
          "hasUpVote": false,
          "hasDownVote": false
        },
        "contentId": {
          "userId": "d5gqchmbgrdj",
          "permlink": "re-dionysusfightswithbriseisagainstepimetheus-1554997352088",
          "refBlockNum": 802
        },
        "meta": {
          "time": "2019-04-11T15:42:33.000Z"
        },
        "author": {
          "userId": "d5gqchmbgrdj",
          "username": "d5gqchmbgrdj"
        }
      }
    ],
    "sequenceKey": null
  }
}
поле full есть, хотя его не должно быть при “contentType”:“mobile”, а поле  mobile отсутствует

**Comment by Format-X22** [comment]
Актуально только для старых комментов, то есть в данном случае не баг.
