### ISSUE TITLE
Рендерилка текстового поля для contentType = mobile

### ISSUE THREAD

**Issue by yurivlad** [GolosChain/prism-service#162]
В текущей реализации, возвращается как тэги div так и пустые тэги, без необходимых доп атрибутов (наприме 'a' без 'href')
Нативный текстовый виджет мобильных устройств предназначен для отображения текста, так-же поддерживая некоторые возможности его форматирования (цвет, ссылки, размер, подчеркивания и т.д)
Поэтому, в целях отображения контента без артефактов, необходимо отдавать мобильным устройствам текст, оставив  html тэги
'h2',
               'h3',
               'h4',
               'h5',
               'h6',
               'blockquote',
               'p',
               'a'(с  href, локальные якоря не поддерживаются),
               'ul',
               'ol',
               'li',
               'b',
               'i',
               'b',
               'strike',
               'code',
               'br'
Также не стоит использовать '\n'(unix newlinie)   и тэг  'br' вместе, надо оставить что-то одно.

**Comment by Format-X22** [comment]
Останется <br>

**Comment by Format-X22** [comment]
nl -> li
em ок
hr -> p
div удалить тег
caption удалить тег с содержимым
pre удалить тег
