### ISSUE TITLE
Необходим ратио (или размер картинки) для мобильных устройств.

### ISSUE THREAD

**Issue by yurivlad** [GolosChain/prism-service#163]
При запросе постов или комментариев, при contentType = mobile, возвращается контет 2-х видов, в том числе картинки. 

Допустим картинка очень маленькая (как в GOLOS под постом юзер добавил пачку мелких картинок-по 60-80 пикселей), я их гружу в виджет картинки - и получается что-то огромное и в пикселях. Это неприемлемо.
Можно картинки сразу грузить в память - тогда будет ее размер. Узнав его, можно изменить способ растягивания.  Но тогда на больших картинках идет постоянное аллоцирование-деалооцирования больших объемов памяти, т.к вместо э эффективных алгоритмов создания картинки строго нужного размера, картинка грузится в память вся.
Это тормозит.
Также возможны артефакты на длинных картинках.
И при подгрузке картинок скролл подергивается, из-за неизвестного размера картинки, и подстраивания под него по процессу загрузки.

Поэтому необходимо отдавая картинки так-же отдавать ее  высоту и ширину.

**Comment by Format-X22** [comment]
После MVP
