### ISSUE TITLE
Поле preview в фиде для мобильных устройств.

### ISSUE THREAD

**Issue by yurivlad** [GolosChain/prism-service#179]
При получении лент постов, в body, в поле preview всегда находятся первый несколько сотен символов поста, и содержание не зависит от переданного параметра contentType.
Для мобильных устройств в ленте фида необходимо показывать либо картинку, либо форматированный текст (поддерживающий ограниченное количество html тэгов).
Поэтому, нужно добавить поле mobilePreview, где будет один отрендеренный для мобильных устройств кусок контента, аналогичный первому элементу из списка в поле body.mobile.

**Comment by Format-X22** [comment]
Ок. Будет отдаваться два элемента где первый это текст без тегов, отсанитайзенный как сейчас, а вторым будет картика - либо первая из тела поста, либо, если такой нет, из эмбеда. Если и там и там ничего нет - будет отсутствовать.

**Comment by Format-X22** [comment]
Нужно понять как оно будет в голосе т.к. там нет ембедов вообще.

**Comment by Format-X22** [comment]
Для голоса не будут учитываться эмбеды и всё.

**Comment by yurivlad** [comment]
поля, которое будет хранить превью для мобильных устройств стоит хранить рядом с preview и назвать preview_mobile.

**Comment by Format-X22** [comment]
Частично реализовано.
