### ISSUE TITLE
Реализовать возможность получить листы без оправления sequenceKey

### ISSUE THREAD

**Issue by bigearsenal** [GolosChain/prism-service#304]
При создание запроса для получения первой страницы без sequenceKey, возвращает ошибка "Unknown or outdated sequence key"
Пример
`
{"id":30,"method":"content.getFeed","jsonrpc":"2.0","params":{"userId":"tst4vjwyfhnm","sortBy":"popular","communityId":"cyber","limit":10,"timeframe":"all","type":"community"}}`

Ошибка
`{"jsonrpc":"2.0","id":30,"error":{"code":410,"message":"Unknown or outdated sequence key"}}`

**Comment by Format-X22** [comment]
На данный момент это адекватное поведение, но в документации стояло что не обязательно. Теперь добавил что поле обязательно.
