### ISSUE TITLE
Получение профиля пользователя.

### ISSUE THREAD

**Issue by yurivlad** [GolosChain/prism-service#320]
при запросе `sending {"method":"content.resolveProfile","params":{"username":"cbfjdhdhjdh","app":"gls"},"jsonrpc":"2.0","id":1}`
ответ - `onMessage {"jsonrpc":"2.0","id":1,"error":{"code":1001,"message":"Internal server error"}}`
В ответе не информативаня ошибка.

**Comment by Format-X22** [comment]
Не воспроизводится, вероятно это были временные проблемы или нужен другой кейс.
