### ISSUE TITLE
Добавить поле method в респоне

### ISSUE THREAD

**Issue by bigearsenal** [GolosChain/prism-service#357]
Пока респон взглядет вот так
{
  "jsonrpc": "2.0",
  "id": 22,
  "result": {
      ...
  }
}

С механизмом запрос-ответ, возможно определить, какая структура данных нужна для декодирования через id.
Но если в real time режиме, сервер отправит данные юзера без запроса, поэтому не определен тип данных для декодирования.
Предложу добавить в респон поле "method", на пример:
{
  "jsonrpc": "2.0",
  "id": 22,
  "method": "content.getProfile",
  "result": {
      ...
  }
}

**Comment by bigearsenal** [comment]
@Format-X22 Я в правилном репозитории создал тикет?

**Comment by Format-X22** [comment]
Мы используем оригинальный [JSON-RPC](https://www.jsonrpc.org), при этом сервер у нас сейчас, если шлёт что-то, шлёт это в виде RPC-нотификации, у которой нет id и она не требует ответа по протоколу (раньше было иначе, но это не удобно). При этом там где происходит это, а происходит это сейчас в нотификациях, содержатся все необходимые данные для того чтобы понять что это и зачем - те же онлайн-нотификации для браузера содержать поле method, но в секции аргументов. При желании можно увидеть это в сокет подключении браузера при получении нотификации о чем-либо.

**Comment by Format-X22** [comment]
Нужно конкретный кейс для чего это и где нужно, абстрактно - не ясно. Тикет закрываю.

**Comment by bigearsenal** [comment]
Если в нотификации есть, то хорошо.
Я пока не занимался нотификацией. Можно отправить пример данные в нотификации?

**Comment by Bacher** [comment]
Вот пример реального сообщения нотификации:
```
{"method":"onlineNotify","jsonrpc":"2.0","params":{"result":[{"fresh":true,"fromUsers":["chingizbaldanov"],"_id":"5d3ec3f4e3a092ad9f968065","eventType":"vote","permlink":"privet","createdAt":"2019-07-29T10:01:24.479Z","updatedAt":"2019-07-29T10:01:24.479Z"}]}}
```

Поле "method" уже есть.

**Comment by bigearsenal** [comment]
Хорошо тогда)
Спасибо!
