### ISSUE TITLE
ios: не приходит список комментариев в профиле 

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/prism-service#358]

**Comment by Format-X22** [comment]
Нужен кейс воспроизведения.

**Comment by daryasattarova** [comment]
1. создаешь комментарий
2. переходишь в свой профиль
3. переходишь на вкладку "Comments"
ожидаемый результат: должен отображаться комментарий, который был создан
ранее
реальный результат: комментарий не приходит

вт, 30 июл. 2019 г. в 11:48, Олег <notifications@github.com>:
