### ISSUE TITLE
content.getFeed возвращает старый sequenceKey

### ISSUE THREAD

**Issue by bigearsenal** [GolosChain/prism-service#369]
content.getFeed возвращает старый sequenceKey, который был отправен запросом
# Запрос
`{
  "id": 77,
  "method": "content.getFeed",
  "jsonrpc": "2.0",
  "params": {
    "sortBy": "timeDesc",
    "userId": "tst42zafqmfo",
    "communityId": "gls",
    "limit": 10,
    "timeframe": "all",
    "type": "community",
    "sequenceKey": "TW9uIEF1ZyAwNSAyMDE5IDAwOjU2OjIwIEdNVCswMDAwIChDb29yZGluYXRlZCBVbml2ZXJzYWwgVGltZSk="
  }
}`

# ответ
`{
  "jsonrpc": "2.0",
  "id": 77,
  "result": {
    "items": [...],
    "sequenceKey": "TW9uIEF1ZyAwNSAyMDE5IDAwOjU2OjIwIEdNVCswMDAwIChDb29yZGluYXRlZCBVbml2ZXJzYWwgVGltZSk="
  }
}`

**Comment by IvanBlacky** [comment]
Closing, as it it already fixed
