### ISSUE TITLE
Лента не учитывает выбранные теги

### ISSUE THREAD

**Issue by beautyfree** [GolosChain/prism-service#373]
@daryasattarova commented on [Tue Jun 04 2019](https://github.com/GolosChain/golos.io/issues/115)

(внутри поста тегов больше нет)
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/1d3e62fb-a445-4569-8025-9defd410763d)

**Comment by daryasattarova** [comment]
выбираю тег - отображаются посты, в которых его нет
