### ISSUE TITLE
не работает content.getProfile с username

### ISSUE THREAD

**Issue by bigearsenal** [GolosChain/prism-service#376]
Юзер не найден по ему юзернейму
userID: 5t2tf1tffghu
userName: ruspowar
bc: 46
## запрос
{"id":33,"method":"content.getProfile","jsonrpc":"2.0","params":{"app":"cyber","username":"ruspowar"}}
## ответ
{"jsonrpc":"2.0","id":33,"error":{"code":404,"message":"Not found"}}

по userID найден такой пользователь

**Comment by IvanBlacky** [comment]
Неверно выставлены параметры: должен быть `"app": "gls"`
