### ISSUE TITLE
не работает content.getFeed с типом subcriptions

### ISSUE THREAD

**Issue by bigearsenal** [GolosChain/prism-service#381]
## Запрос
`{
  "id": 35,
  "method": "content.getFeed",
  "jsonrpc": "2.0",
  "params": {
    "sortBy": "timeDesc",
    "userId": "tst11fwgbkqo",
    "type": "subscriptions",
    "limit": 10
  }
}`

## Ответ
`{"jsonrpc":"2.0","id":35,"result":{"items":[],"sequenceKey":null}}`

юзер уже подписал на 3 других пользователей

**Comment by IvanBlacky** [comment]
Closing, as it is already fixed
